export const GOOGLE_FONTS = [
    // Sans Serif
    { name: 'Inter', value: '"Inter", sans-serif', category: 'Sans Serif' },
    { name: 'Roboto', value: '"Roboto", sans-serif', category: 'Sans Serif' },
    { name: 'Open Sans', value: '"Open Sans", sans-serif', category: 'Sans Serif' },
    { name: 'Lato', value: '"Lato", sans-serif', category: 'Sans Serif' },
    { name: 'Montserrat', value: '"Montserrat", sans-serif', category: 'Sans Serif' },
    { name: 'Poppins', value: '"Poppins", sans-serif', category: 'Sans Serif' },
    { name: 'Raleway', value: '"Raleway", sans-serif', category: 'Sans Serif' },
    { name: 'Ubuntu', value: '"Ubuntu", sans-serif', category: 'Sans Serif' },
    { name: 'Nunito', value: '"Nunito", sans-serif', category: 'Sans Serif' },
    { name: 'Oswald', value: '"Oswald", sans-serif', category: 'Sans Serif' },
    { name: 'Mukta', value: '"Mukta", sans-serif', category: 'Sans Serif' },
    { name: 'Work Sans', value: '"Work Sans", sans-serif', category: 'Sans Serif' },
    { name: 'Quicksand', value: '"Quicksand", sans-serif', category: 'Sans Serif' },
    { name: 'Kanit', value: '"Kanit", sans-serif', category: 'Sans Serif' },
    { name: 'Heebo', value: '"Heebo", sans-serif', category: 'Sans Serif' },
    { name: 'Karla', value: '"Karla", sans-serif', category: 'Sans Serif' },
    { name: 'Outfit', value: '"Outfit", sans-serif', category: 'Sans Serif' },
    { name: 'Josefin Sans', value: '"Josefin Sans", sans-serif', category: 'Sans Serif' },
    { name: 'Bebas Neue', value: '"Bebas Neue", sans-serif', category: 'Sans Serif' },
    { name: 'PT Sans', value: '"PT Sans", sans-serif', category: 'Sans Serif' },

    // Serif
    { name: 'Playfair Display', value: '"Playfair Display", serif', category: 'Serif' },
    { name: 'Merriweather', value: '"Merriweather", serif', category: 'Serif' },
    { name: 'Lora', value: '"Lora", serif', category: 'Serif' },
    { name: 'PT Serif', value: '"PT Serif", serif', category: 'Serif' },
    { name: 'Noto Serif', category: 'Serif', value: '"Noto Serif", serif' },
    { name: 'Crimson Text', category: 'Serif', value: '"Crimson Text", serif' },
    { name: 'Arvo', category: 'Serif', value: '"Arvo", serif' },
    { name: 'Eb Garamond', category: 'Serif', value: '"EB Garamond", serif' },
    { name: 'Libre Baskerville', category: 'Serif', value: '"Libre Baskerville", serif' },
    { name: 'Cormorant Garamond', category: 'Serif', value: '"Cormorant Garamond", serif' },
    { name: 'Cinzel', category: 'Serif', value: '"Cinzel", serif' },
    { name: 'Old Standard TT', category: 'Serif', value: '"Old Standard TT", serif' },
    { name: 'Bodoni Moda', category: 'Serif', value: '"Bodoni Moda", serif' },

    // Display
    { name: 'Pacifico', category: 'Display', value: '"Pacifico", cursive' },
    { name: 'Lobster', category: 'Display', value: '"Lobster", cursive' },
    { name: 'Comfortaa', category: 'Display', value: '"Comfortaa", cursive' },
    { name: 'Righteous', category: 'Display', value: '"Righteous", cursive' },
    { name: 'Dancing Script', category: 'Display', value: '"Dancing Script", cursive' },
    { name: 'Permanent Marker', category: 'Display', value: '"Permanent Marker", cursive' },
    { name: 'Abril Fatface', category: 'Display', value: '"Abril Fatface", cursive' },
    { name: 'Satisfy', category: 'Display', value: '"Satisfy", cursive' },
    { name: 'Courgette', category: 'Display', value: '"Courgette", cursive' },
    { name: 'Great Vibes', category: 'Display', value: '"Great Vibes", cursive' },
    { name: 'Yellowtail', category: 'Display', value: '"Yellowtail", cursive' },
    { name: 'Monoton', category: 'Display', value: '"Monoton", cursive' },
    { name: 'Bungee', category: 'Display', value: '"Bungee", cursive' },
    { name: 'Bungee Shade', category: 'Display', value: '"Bungee Shade", cursive' },
    { name: 'Special Elite', category: 'Display', value: '"Special Elite", cursive' },
    { name: 'Shadows Into Light', category: 'Display', value: '"Shadows Into Light", cursive' },
    { name: 'Patua One', category: 'Display', value: '"Patua One", cursive' },

    // Monospace
    { name: 'Roboto Mono', category: 'Monospace', value: '"Roboto Mono", monospace' },
    { name: 'Source Code Pro', category: 'Monospace', value: '"Source Code Pro", monospace' },
    { name: 'Space Mono', category: 'Monospace', value: '"Space Mono", monospace' },
    { name: 'Inconsolata', category: 'Monospace', value: '"Inconsolata", monospace' },
    { name: 'Fira Code', category: 'Monospace', value: '"Fira Code", monospace' },
    { name: 'JetBrains Mono', category: 'Monospace', value: '"JetBrains Mono", monospace' },
    { name: 'VT323', category: 'Monospace', value: '"VT323", monospace' },
    { name: 'Courier Prime', category: 'Monospace', value: '"Courier Prime", monospace' },
    { name: 'Major Mono Display', category: 'Monospace', value: '"Major Mono Display", monospace' },
];
