import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    de: {
        // Sidebar
        dashboard: 'Übersicht',
        newInvoice: 'Neue Rechnung',
        quotes: 'Angebote',
        archive: 'Archiv',
        reports: 'Berichte',
        expenses: 'Ausgaben',
        recurring: 'Wiederkehrend',
        settings: 'Einstellungen',

        // Common / Actions
        save: 'Speichern',
        cancel: 'Abbrechen',
        delete: 'Löschen',
        edit: 'Bearbeiten',
        print: 'Drucken',
        loading: 'Lädt...',
        total: 'Gesamtbetrag',
        status: 'Status',
        date: 'Datum',
        customer: 'Kunde',
        invoiceNumber: 'Rechnungs-Nr.',
        quoteNumber: 'Angebots-Nr.',
        saveAndPrint: 'Speichern & Drucken',
        actions: 'Aktionen',
        back: 'Zurück',
        convertToInvoice: 'In Rechnung umwandeln',
        validUntil: 'Gültig bis',
        newQuote: 'Neues Angebot',
        quote: 'Angebot',
        proforma: 'Proforma',

        // Dashboard
        welcome: 'Willkommen',
        revenue: 'Gesamtumsatz',
        netProfit: 'Gewinn (Netto)',
        recentInvoices: 'Aktuelle Rechnungen',
        overviewText: 'Hier ist die Übersicht deiner Rechnungen und Finanzen.',

        // Settings
        companySettings: 'Firmeneinstellungen',
        language: 'Sprache',
        appLanguageLabel: 'Anwendungs-Sprache',
        invoiceLanguageLabel: 'Fatura-Sprache (Druck)',
        plan: 'Paket',
        standard: 'Standard',
        premium: 'Premium',
        bankDetails: 'Bankverbindung',
        onlinePayments: 'Online-Zahlungen',
        generalInfo: 'Allgemeine Informationen',
        taxSettings: 'Steuer-Einstellungen',
        currency: 'Währung',
        taxRate: 'Steuersatz',
        companyName: 'Firmenname',
        owner: 'Inhaber',
        street: 'Straße',
        houseNum: 'Haus-Nr.',
        zip: 'PLZ',
        city: 'Stadt',
        phone: 'Telefon',
        email: 'E-Mail',
        taxId: 'Steuernummer',
        vatId: 'USt-IdNr.',
        bankName: 'Bankname',
        iban: 'IBAN',
        paymentTerms: 'Zahlungsbedingungen',
        paymentInfo: 'Zahlungsinformationen',
        taxInfo: 'Steuerliche Angaben',

        // Invoice Form
        customerInfo: 'Kundeninformationen',
        vehicleDetails: 'Fahrzeug & Details',
        items: 'Leistungen / Ersatzteile',
        description: 'Beschreibung',
        quantity: 'Menge',
        price: 'Einzelpreis',
        addRow: 'Zeile hinzufügen',
        subtotal: 'Zwischensumme',
        tax: 'MwSt.',
        vehicle: 'Fahrzeug',
        plate: 'Kennzeichen',
        km: 'KM-Stand',

        // Statuses
        draft: 'Entwurf',
        sent: 'Gesendet',
        paid: 'Bezahlt',
        partial: 'Teilweise',
        overdue: 'Überfällig',
        invoiceDetails: 'Rechnungsdetails',
        printPdf: 'Drucken / PDF',
        payOnline: 'Online bezahlen',
        payWithPaypal: 'Mit PayPal bezahlen',
        payWithStripe: 'Mit Kreditkarte bezahlen',
        invoiceNotFound: 'Rechnung nicht gefunden',
        backToArchive: 'Zurück zum Archiv',
        saveSuccessful: 'Erfolgreich gespeichert!',
        recurringInvoices: 'Wiederkehrende Rechnungen',
        recurringInvoicesDesc: 'Vorlagen für regelmäßige Rechnungsstellung.',
        createTemplate: 'Vorlage erstellen',
        frequency: 'Frequenz',
        weekly: 'Wöchentlich',
        monthly: 'Monatlich',
        quarterly: 'Quartalsweise',
        yearly: 'Jährlich',
        upcoming: 'demnächst',
        noRecurring: 'Keine wiederkehrenden Rechnungen eingerichtet.',
        spareParts: 'Ersatzteile',
        receipts: 'Belege',
        export: 'Exportieren',
        addExpense: 'Ausgabe hinzufügen',
        amount: 'Betrag',
        noData: 'Keine Daten vorhanden',
        category: 'Kategorie',
        rent: 'Miete / Nebenkosten',
        marketing: 'Marketing',
        software: 'Software / Abos',
        insurance: 'Versicherungen',
        others: 'Sonstiges',
        'Yedek Parçalar': 'Ersatzteile',
        'Işçilik / Malzeme': 'Arbeit / Material',
        businessStats: 'Geschäftsstatistik',
        industry: 'Branche',
        automotive: 'KFZ-Werkstatt',
        generalService: 'Dienstleistung / Handel',
        projectDetails: 'Projekt & Referenz',
        reference: 'Referenz-Nr.',
        extraNote: 'Zusatzinfo',
        genericService: 'Leistung / Produkt',
        inProfit: 'Im Plus (Kârdasın)',
        inLoss: 'Im Minus (Zarardasın)',
        logoDisplayMode: 'Logo & Firmenname Anzeige',
        logoOnly: 'Nur Logo',
        nameOnly: 'Nur Firmenname',
        bothLogoOnTop: 'Beides - Logo oben',
        premiumApiSection: 'Zahlungs-Schnittstellen (API Dashboard)',
        premiumApiHint: '* Diese Daten werden im Premium-Paket verwendet, um Zahlungen über Stripe und PayPal automatisch im System zu verarbeiten.',
        premiumOnly: 'NUR PREMIUM',

        // Auth
        login: 'Anmelden',
        register: 'Registrieren',
        logout: 'Abmelden',
        password: 'Passwort',
        confirmPassword: 'Passwort bestätigen',
        fullName: 'Vollständiger Name',
        createAccount: 'Konto erstellen',
        alreadyHaveAccount: 'Haben Sie bereits ein Konto?',
        noAccount: 'Noch kein Konto?',
        signUp: 'Registrieren',
        signIn: 'Anmelden',
        rememberMe: 'Angemeldet bleiben',
        forgotPassword: 'Passwort vergessen?',
        termsAgree: 'Ich akzeptiere die Nutzungsbedingungen',
        welcomeBack: 'Willkommen zurück!',
        fillAllFields: 'Bitte alle Felder ausfüllen',
        invalidCredentials: 'Ungültige E-Mail oder Passwort',
        required: 'Erforderlich',
        passwordMismatch: 'Passwörter stimmen nicht überein',
        mustAcceptTerms: 'Sie müssen die Bedingungen akzeptieren',

        // Landing
        heroTitle: 'Professionelle Rechnungen in Sekunden',
        heroSubtitle: 'Die einfachste Art, Rechnungen und Finanzen für kleine Unternehmen zu verwalten',
        getStarted: 'Jetzt starten',
        learnMore: 'Mehr erfahren',
        features: 'Funktionen',
        perMonth: '/ Monat',
        freeTrial: 'Kostenlos testen',
        mostPopular: 'Beliebteste',
        standardPlan: 'Standard',
        premiumPlan: 'Premium',
        multiLanguageInvoices: 'Mehrsprachige Rechnungen',
        multiLanguageInvoicesDesc: 'Rechnungen in 5 Sprachen erstellen',
        financialTracking: 'Finanzüberwachung',
        financialTrackingDesc: 'Umsatz, Ausgaben und Gewinn verfolgen',
        industryTemplates: 'Branchen-Vorlagen',
        industryTemplatesDesc: 'Automotive und allgemeine Geschäfte',
        secureStorage: 'Sicherer Speicher',
        secureStorageDesc: 'Ihre Daten sind sicher und verschlüsselt',
        mobileResponsive: 'Mobil optimiert',
        mobileResponsiveDesc: 'Funktioniert perfekt auf allen Geräten',
        customBranding: 'Individuelles Branding',
        customBrandingDesc: 'Fügen Sie Ihr Logo und Firmendaten hinzu',
        onlinePaymentsDesc: 'Zahlungen via PayPal & Stripe akzeptieren',
        fastEasy: 'Schnell & Einfach',
        fastEasyDesc: 'Rechnungen in Sekunden erstellen',
        unlimitedInvoices: 'Unbegrenzte Rechnungen',
        basicReports: 'Basis-Berichte',
        emailSupport: 'E-Mail-Support',
        mobileAccess: 'Mobile Zugang',
        everythingInStandard: 'Alles aus Standard',
        advancedReports: 'Erweiterte Analysen & Berichte',
        apiIntegrations: 'API-Integrationen (Stripe, PayPal)',
        prioritySupport: 'Prioritäts-Support',
        multiUser: 'Mehrbenutzerzugriff',
        customDomain: 'Eigene Domain',
        startPremium: 'Premium starten',
        featuresSubtitle: 'Alles was Sie brauchen, um Ihre Geschäftsfinanzen zu verwalten',
        pricingSubtitle: 'Wählen Sie den Plan, der zu Ihnen passt',
        footerTagline: 'Professionelle Rechnungsstellung leicht gemacht',
        product: 'Produkt',
        company: 'Unternehmen',
        about: 'Über uns',
        contact: 'Kontakt',
        privacy: 'Datenschutz',
        terms: 'Nutzungsbedingungen',
        perYear: '/ Jahr',
        appInAction: 'BayRechnung in Aktion',
        appInActionDesc: 'Erstellen Sie professionelle Rechnungen mit nur wenigen Klicks',
        easyInvoiceCreation: '⚡ Einfache Rechnungserstellung',
        easyInvoiceCreationDesc: 'Intuitive Oberfläche macht das Erstellen von Rechnungen schnell und einfach. Positionen hinzufügen, Summen werden automatisch berechnet.',
        professionalPDFs: '📄 Professionelle PDFs',
        professionalPDFsDesc: 'Erzeugen Sie schöne, druckfertige Rechnungen, die Ihre Kunden beeindrucken und rechtliche Anforderungen erfüllen.'
    },
    en: {
        dashboard: 'Dashboard',
        newInvoice: 'New Invoice',
        archive: 'Archive',
        reports: 'Reports',
        expenses: 'Expenses',
        recurring: 'Recurring',
        settings: 'Settings',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        print: 'Print',
        loading: 'Loading...',
        total: 'Total Amount',
        status: 'Status',
        date: 'Date',
        customer: 'Customer',
        invoiceNumber: 'Invoice No.',
        saveAndPrint: 'Save & Print',
        actions: 'Actions',
        back: 'Back',
        welcome: 'Welcome',
        revenue: 'Total Revenue',
        netProfit: 'Net Profit',
        recentInvoices: 'Recent Invoices',
        overviewText: "Here is the overview of your invoices and finances.",
        companySettings: 'Company Settings',
        language: 'Language',
        appLanguageLabel: 'App Language',
        invoiceLanguageLabel: 'Invoice Language (PDF)',
        plan: 'Plan',
        standard: 'Standard',
        premium: 'Premium',
        bankDetails: 'Bank Details',
        onlinePayments: 'Online Payments',
        generalInfo: 'General Information',
        taxSettings: 'Tax Settings',
        currency: 'Currency',
        taxRate: 'Tax Rate',
        companyName: 'Company Name',
        owner: 'Owner',
        street: 'Street',
        houseNum: 'House No.',
        zip: 'ZIP Code',
        city: 'City',
        phone: 'Phone',
        email: 'Email',
        taxId: 'Tax ID',
        vatId: 'VAT ID',
        bankName: 'Bank Name',
        iban: 'IBAN',
        paymentTerms: 'Payment Terms',
        paymentInfo: 'Payment Information',
        taxInfo: 'Tax Information',
        customerInfo: 'Customer Information',
        vehicleDetails: 'Vehicle & Details',
        items: 'Items / Services',
        description: 'Description',
        quantity: 'Quantity',
        price: 'Unit Price',
        addRow: 'Add Row',
        subtotal: 'Subtotal',
        tax: 'VAT',
        vehicle: 'Vehicle',
        plate: 'Plate',
        km: 'Mileage',
        draft: 'Draft',
        sent: 'Sent',
        paid: 'Paid',
        partial: 'Partial',
        overdue: 'Overdue',
        invoiceDetails: 'Invoice Details',
        printPdf: 'Print / PDF',
        payOnline: 'Pay Online',
        payWithPaypal: 'Pay with PayPal',
        payWithStripe: 'Pay with Credit Card',
        invoiceNotFound: 'Invoice Not Found',
        backToArchive: 'Back to Archive',
        saveSuccessful: 'Saved successfully!',
        recurringInvoices: 'Recurring Invoices',
        recurringInvoicesDesc: 'Templates for regular invoicing.',
        createTemplate: 'Create Template',
        frequency: 'Frequency',
        weekly: 'Weekly',
        monthly: 'Monthly',
        quarterly: 'Quarterly',
        yearly: 'Yearly',
        upcoming: 'upcoming',
        noRecurring: 'No recurring invoices set up.',
        spareParts: 'Spare Parts',
        receipts: 'Receipts',
        export: 'Export',
        addExpense: 'Add Expense',
        amount: 'Amount',
        noData: 'No data available',
        category: 'Category',
        rent: 'Rent / Utilities',
        marketing: 'Marketing',
        software: 'Software / Subs',
        insurance: 'Insurances',
        others: 'Others',
        businessStats: 'Business Statistics',
        industry: 'Industry',
        automotive: 'Automotive / Mechanic',
        generalService: 'General Service / Trade',
        projectDetails: 'Project & Reference',
        reference: 'Reference No.',
        extraNote: 'Extra Info',
        genericService: 'Service / Product',
        inProfit: 'In Profit',
        inLoss: 'In Loss',
        logoDisplayMode: 'Logo & Company Name Display',
        logoOnly: 'Logo Only',
        nameOnly: 'Company Name Only',
        bothLogoOnTop: 'Both - Logo on Top',
        premiumApiSection: 'Payment Interfaces (API Dashboard)',
        premiumApiHint: '* These details are used in the Premium plan to automatically process payments via Stripe and PayPal.',
        premiumOnly: 'PREMIUM ONLY',

        // Auth
        login: 'Login',
        register: 'Register',
        logout: 'Logout',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        fullName: 'Full Name',
        createAccount: 'Create Account',
        alreadyHaveAccount: 'Already have an account?',
        noAccount: 'No account?',
        signUp: 'Sign up',
        signIn: 'Sign in',
        rememberMe: 'Remember me',
        forgotPassword: 'Forgot password?',
        termsAgree: 'I agree to Terms & Conditions',
        welcomeBack: 'Welcome back!',
        fillAllFields: 'Please fill all fields',
        invalidCredentials: 'Invalid email or password',
        required: 'Required',
        passwordMismatch: 'Passwords do not match',
        mustAcceptTerms: 'You must accept terms',

        // Landing
        heroTitle: 'Professional Invoices in Seconds',
        heroSubtitle: 'The simplest way to manage invoices and finances for small businesses',
        getStarted: 'Get Started',
        learnMore: 'Learn More',
        features: 'Features',
        perMonth: '/ month',
        freeTrial: 'Free Trial',
        mostPopular: 'Most Popular',
        standardPlan: 'Standard',
        premiumPlan: 'Premium',
        multiLanguageInvoices: 'Multi-language Invoices',
        multiLanguageInvoicesDesc: 'Create invoices in 5 languages',
        financialTracking: 'Financial Tracking',
        financialTrackingDesc: 'Track revenue, expenses, and profit',
        industryTemplates: 'Industry Templates',
        industryTemplatesDesc: 'Automotive and general business',
        secureStorage: 'Secure Storage',
        secureStorageDesc: 'Your data is safe and encrypted',
        mobileResponsive: 'Mobile Responsive',
        mobileResponsiveDesc: 'Works perfectly on all devices',
        customBranding: 'Custom Branding',
        customBrandingDesc: 'Add your logo and company details',
        onlinePaymentsDesc: 'Accept payments via PayPal & Stripe',
        fastEasy: 'Fast & Easy',
        fastEasyDesc: 'Create invoices in seconds',
        unlimitedInvoices: 'Unlimited invoices',
        basicReports: 'Basic reports',
        emailSupport: 'Email support',
        mobileAccess: 'Mobile access',
        everythingInStandard: 'Everything in Standard',
        advancedReports: 'Advanced analytics & reports',
        apiIntegrations: 'API integrations (Stripe, PayPal)',
        prioritySupport: 'Priority support',
        multiUser: 'Multi-user access',
        customDomain: 'Custom domain',
        startPremium: 'Start Premium',
        featuresSubtitle: 'Everything you need to manage your business finances',
        pricingSubtitle: 'Choose the plan that fits your needs',
        footerTagline: 'Professional invoicing made simple',
        product: 'Product',
        company: 'Company',
        about: 'About',
        contact: 'Contact',
        privacy: 'Privacy',
        terms: 'Terms',
        perYear: '/ year',
        appInAction: 'See BayRechnung in Action',
        appInActionDesc: 'Create professional invoices in just a few clicks',
        easyInvoiceCreation: '⚡ Easy Invoice Creation',
        easyInvoiceCreationDesc: 'Intuitive interface makes creating invoices fast and simple. Add items, calculate totals automatically.',
        professionalPDFs: '📄 Professional PDFs',
        professionalPDFsDesc: 'Generate beautiful, print-ready invoices that impress your clients and meet legal requirements.'
    },
    tr: {
        dashboard: 'Genel Bakış',
        newInvoice: 'Yeni Fatura',
        archive: 'Arşiv',
        reports: 'Raporlar',
        expenses: 'Giderler',
        recurring: 'Tekrarlayan',
        settings: 'Ayarlar',
        save: 'Kaydet',
        cancel: 'İptal',
        delete: 'Sil',
        edit: 'Düzenle',
        print: 'Yazdır',
        loading: 'Yükleniyor...',
        total: 'Toplam Tutar',
        status: 'Durum',
        date: 'Tarih',
        customer: 'Müşteri',
        invoiceNumber: 'Fatura No',
        saveAndPrint: 'Kaydet ve Yazdır',
        actions: 'İşlemler',
        back: 'Geri',
        welcome: 'Hoş geldiniz',
        revenue: 'Toplam Ciro',
        netProfit: 'Net Kar',
        recentInvoices: 'Son Faturalar',
        overviewText: 'Fatura ve finansal durumunuza buradan göz atabilirsiniz.',
        companySettings: 'Şirket Ayarları',
        language: 'Dil',
        appLanguageLabel: 'Uygulama Dili',
        invoiceLanguageLabel: 'Fatura Dili (Çıktı)',
        plan: 'Paket',
        standard: 'Standart',
        premium: 'Premium',
        bankDetails: 'Banka Bilgileri',
        onlinePayments: 'Online Ödemeler',
        generalInfo: 'Genel Bilgiler',
        taxSettings: 'Vergi Ayarları',
        currency: 'Para Birimi',
        taxRate: 'Vergi Oranı',
        companyName: 'Şirket Adı',
        owner: 'Sahibi',
        street: 'Sokak/Cadde',
        houseNum: 'Bina No',
        zip: 'Posta Kodu',
        city: 'Şehir',
        phone: 'Telefon',
        email: 'E-Posta',
        taxId: 'Vergi Numarası',
        vatId: 'KDV Numarası',
        bankName: 'Banka Adı',
        iban: 'IBAN',
        paymentTerms: 'Ödeme Koşulları',
        paymentInfo: 'Ödeme Bilgileri',
        taxInfo: 'Vergi Bilgileri',
        customerInfo: 'Müşteri Bilgileri',
        vehicleDetails: 'Araç ve Detaylar',
        items: 'Hizmetler / Parçalar',
        description: 'Açıklama',
        quantity: 'Adet',
        price: 'Birim Fiyat',
        addRow: 'Satır Ekle',
        subtotal: 'Ara Toplam',
        tax: 'KDV',
        vehicle: 'Araç',
        plate: 'Plaka',
        km: 'Kilometre',
        draft: 'Taslak',
        sent: 'Gönderildi',
        paid: 'Ödendi',
        partial: 'Kısmi Ödeme',
        overdue: 'Gecikmiş',
        invoiceDetails: 'Fatura Detayları',
        printPdf: 'Yazdır / PDF',
        payOnline: 'Çevrimiçi Öde',
        payWithPaypal: 'PayPal ile Öde',
        payWithStripe: 'Kredi Kartı ile Öde',
        invoiceNotFound: 'Fatura Bulunamadı',
        backToArchive: 'Arşive Dön',
        saveSuccessful: 'Başarıyla kaydedildi!',
        recurringInvoices: 'Tekrarlayan Faturalar',
        recurringInvoicesDesc: 'Düzenli faturalandırma için şablonlar.',
        createTemplate: 'Şablon Oluştur',
        frequency: 'Sıklık',
        weekly: 'Haftalık',
        monthly: 'Aylık',
        quarterly: 'Üç Aylık',
        yearly: 'Yıllık',
        upcoming: 'yakında',
        noRecurring: 'Tekrarlayan fatura bulunmuyor.',
        spareParts: 'Yedek Parçalar',
        receipts: 'Fişler / Makbuzlar',
        export: 'Dışa Aktar',
        addExpense: 'Gider Ekle',
        amount: 'Tutar',
        noData: 'Veri bulunmuyor',
        category: 'Kategori',
        rent: 'Kira / Giderler',
        marketing: 'Pazarlama',
        software: 'Yazılım / Abonelik',
        insurance: 'Sigortalar',
        others: 'Diğer',
        businessStats: 'İş İstatistikleri',
        industry: 'Sektör',
        automotive: 'Oto Tamir / Servis',
        generalService: 'Genel Hizmet / Ticaret',
        projectDetails: 'Proje ve Referans',
        reference: 'Referans No',
        extraNote: 'Ek Bilgi',
        genericService: 'Hizmet / Ürün',
        inProfit: 'Kârdasın',
        inLoss: 'Zarardasın',
        logoDisplayMode: 'Logo & Firma İsmi Gösterimi',
        logoOnly: 'Sadece Logo',
        nameOnly: 'Sadece Firma İsmi',
        bothLogoOnTop: 'Her İkisi - Logo Üstte',
        premiumApiSection: 'Ödeme Arayüzleri (API Paneli)',
        premiumApiHint: '* Bu bilgiler Premium pakette Stripe ve PayPal üzerinden ödemeleri otomatik işlemek için kullanılır.',
        premiumOnly: 'SADECE PREMIUM',

        // Auth
        login: 'Giriş Yap',
        register: 'Kayıt Ol',
        logout: 'Çıkış Yap',
        password: 'Şifre',
        confirmPassword: 'Şifre Tekrar',
        fullName: 'Ad Soyad',
        createAccount: 'Hesap Oluştur',
        alreadyHaveAccount: 'Zaten hesabınız var mı?',
        noAccount: 'Hesabınız yok mu?',
        signUp: 'Kayıt Ol',
        signIn: 'Giriş Yap',
        rememberMe: 'Beni hatırla',
        forgotPassword: 'Şifremi unuttum?',
        termsAgree: 'Koşulları kabul ediyorum',
        welcomeBack: 'Tekrar hoş geldiniz!',
        fillAllFields: 'Lütfen tüm alanları doldurun',
        invalidCredentials: 'Geçersiz e-posta veya şifre',
        required: 'Gerekli',
        passwordMismatch: 'Şifreler eşleşmiyor',
        mustAcceptTerms: 'Koşulları kabul etmelisiniz',

        // Landing
        heroTitle: 'Saniyeler İçinde Profesyonel Faturalar',
        heroSubtitle: 'Küçük işletmeler için fatura ve finans yönetiminin en basit yolu',
        getStarted: 'Şimdi Başla',
        learnMore: 'Daha Fazla Bilgi',
        features: 'Özellikler',
        pricing: 'Fiyatlandırma',
        perMonth: '/ ay',
        freeTrial: 'Ücretsiz Deneme',
        mostPopular: 'En Popüler',
        multiLanguageInvoices: 'Çok Dilli Faturalar',
        multiLanguageInvoicesDesc: '5 dilde fatura oluşturun',
        financialTracking: 'Finansal Takip',
        financialTrackingDesc: 'Gelir, gider ve karı takip edin',
        industryTemplates: 'Sektör Şablonları',
        industryTemplatesDesc: 'Otomotiv ve genel işletme',
        secureStorage: 'Güvenli Depolama',
        secureStorageDesc: 'Verileriniz güvenli ve şifreli',
        mobileResponsive: 'Mobil Uyumlu',
        mobileResponsiveDesc: 'Tüm cihazlarda mükemmel çalışır',
        customBranding: 'Özel Markalaşma',
        customBrandingDesc: 'Logonuzu ve firma bilgilerinizi ekleyin',
        onlinePaymentsDesc: 'PayPal ve Stripe ile ödeme kabul edin',
        fastEasy: 'Hızlı ve Kolay',
        fastEasyDesc: 'Saniyeler içinde fatura oluşturun',
        unlimitedInvoices: 'Sınırsız fatura',
        basicReports: 'Temel raporlar',
        emailSupport: 'E-posta desteği',
        mobileAccess: 'Mobil erişim',
        everythingInStandard: 'Standarttaki her şey',
        advancedReports: 'Gelişmiş analiz ve raporlar',
        apiIntegrations: 'API entegrasyonları (Stripe, PayPal)',
        prioritySupport: 'Öncelikli destek',
        multiUser: 'Çok kullanıcılı erişim',
        customDomain: 'Özel domain',
        startPremium: 'Premium Başlat',
        featuresSubtitle: 'İş finanslarınızı yönetmek için ihtiyacınız olan her şey',
        pricingSubtitle: 'İhtiyacınıza uygun planı seçin',
        footerTagline: 'Profesyonel faturalandırma artık çok kolay',
        product: 'Ürün',
        company: 'Şirket',
        about: 'Hakkımızda',
        contact: 'İletişim',
        privacy: 'Gizlilik',
        terms: 'Koşullar',
        perYear: '/ yıl',
        appInAction: 'BayRechnung\'u İşbaşında Görün',
        appInActionDesc: 'Sadece birkaç tıklamayla profesyonel faturalar oluşturun',
        easyInvoiceCreation: '⚡ Kolay Fatura Oluşturma',
        easyInvoiceCreationDesc: 'Sezgisel arayüz fatura oluşturmayı hızlı ve basit hale getirir. Öğe ekleyin, toplamlar otomatik hesaplanır.',
        professionalPDFs: '📄 Profesyonel PDF\'ler',
        professionalPDFsDesc: 'Müşterilerinizi etkileyen ve yasal gereklilikleri karşılayan güzel, baskıya hazır faturalar oluşturun.',
        paidInvoices: 'Ödenen Faturalar',
        overdueInvoices: 'Gecikmiş Faturalar',
        topClients: 'En İyi Müşteriler'
    },
    fr: {
        dashboard: 'Tableau de bord',
        newInvoice: 'Nouvelle facture',
        archive: 'Archives',
        reports: 'Rapports',
        expenses: 'Dépenses',
        recurring: 'Récurrent',
        settings: 'Paramètres',
        save: 'Enregistrer',
        cancel: 'Annuler',
        delete: 'Supprimer',
        edit: 'Modifier',
        print: 'Imprimer',
        loading: 'Chargement...',
        total: 'Montant total',
        status: 'Statut',
        date: 'Date',
        customer: 'Client',
        invoiceNumber: 'N° de facture',
        saveAndPrint: 'Enregistrer et Imprimer',
        actions: 'Actions',
        back: 'Retour',
        welcome: 'Bienvenue',
        revenue: 'Chiffre d\'affaires',
        netProfit: 'Bénéfice net',
        recentInvoices: 'Factures récentes',
        overviewText: 'Voici l\'aperçu de vos factures et de vos finances.',
        companySettings: 'Paramètres de l\'entreprise',
        language: 'Langue',
        appLanguageLabel: 'Langue de l\'application',
        invoiceLanguageLabel: 'Langue de la facture (PDF)',
        plan: 'Forfait',
        standard: 'Standard',
        premium: 'Premium',
        bankDetails: 'Détails bancaires',
        onlinePayments: 'Paiements en ligne',
        generalInfo: 'Informations générales',
        taxSettings: 'Paramètres fiscaux',
        currency: 'Devise',
        taxRate: 'Taux de taxe',
        companyName: 'Nom de l\'entreprise',
        owner: 'Propriétaire',
        street: 'Rue',
        houseNum: 'N° de maison',
        zip: 'Code postal',
        city: 'Ville',
        phone: 'Téléphone',
        email: 'Email',
        taxId: 'ID fiscal',
        vatId: 'N° TVA',
        bankName: 'Nom de la banque',
        iban: 'IBAN',
        paymentTerms: 'Conditions de paiement',
        paymentInfo: 'Informations de paiement',
        taxInfo: 'Informations fiscales',
        customerInfo: 'Informations client',
        vehicleDetails: 'Véhicule et détails',
        items: 'Articles / Services',
        description: 'Description',
        quantity: 'Quantité',
        price: 'Prix unitaire',
        addRow: 'Ajouter une ligne',
        subtotal: 'Sous-total',
        tax: 'TVA',
        vehicle: 'Véhicule',
        plate: 'Plaque',
        km: 'Kilométrage',
        draft: 'Brouillon',
        sent: 'Envoyé',
        paid: 'Payé',
        partial: 'Partiel',
        overdue: 'En retard',
        invoiceDetails: 'Détails de la facture',
        printPdf: 'Imprimer / PDF',
        payOnline: 'Payer en ligne',
        payWithPaypal: 'Payer avec PayPal',
        payWithStripe: 'Payer par carte bancaire',
        invoiceNotFound: 'Facture non trouvée',
        backToArchive: 'Retour aux archives',
        noRecurring: 'Aucune facture récurrente configurée.',
        spareParts: 'Pièces de rechange',
        receipts: 'Recettes',
        export: 'Exporter',
        addExpense: 'Ajouter une dépense',
        amount: 'Montant',
        noData: 'Aucune donnée disponible',
        category: 'Catégorie',
        rent: 'Loyer / Charges',
        marketing: 'Marketing',
        software: 'Logiciels / Abos',
        insurance: 'Assurances',
        others: 'Autres',
        businessStats: 'Statistiques de l\'entreprise',
        industry: 'Secteur',
        automotive: 'Garage / Mécanique',
        generalService: 'Service général / Commerce',
        projectDetails: 'Projet et référence',
        reference: 'Référence n°',
        extraNote: 'Info supplémentaire',
        genericService: 'Prestation / Produit',
        inProfit: 'En Profit',
        inLoss: 'En Perte',
        logoDisplayMode: 'Affichage Logo & Nom',
        logoOnly: 'Logo uniquement',
        nameOnly: 'Nom de l\'entreprise uniquement',
        bothLogoOnTop: 'Les deux - Logo en haut',
        premiumApiSection: 'Interfaces de paiement (Tableau de bord API)',
        premiumApiHint: '* Ces données sont utilisées dans le plan Premium pour traiter automatiquement les paiements via Stripe et PayPal.',
        premiumOnly: 'PREMIUM UNIQUEMENT',
        saveSuccessful: 'Enregistré avec succès !',

        // Auth
        login: 'Connexion',
        register: 'S\'inscrire',
        logout: 'Déconnexion',
        password: 'Mot de passe',
        confirmPassword: 'Confirmer le mot de passe',
        fullName: 'Nom complet',
        createAccount: 'Créer un compte',
        alreadyHaveAccount: 'Vous avez déjà un compte?',
        noAccount: 'Pas de compte?',
        signUp: 'S\'inscrire',
        signIn: 'Se connecter',
        rememberMe: 'Se souvenir de moi',
        forgotPassword: 'Mot de passe oublié?',
        termsAgree: 'J\'accepte les conditions',
        welcomeBack: 'Bon retour!',
        fillAllFields: 'Veuillez remplir tous les champs',
        invalidCredentials: 'Email ou mot de passe invalide',
        required: 'Requis',
        passwordMismatch: 'Les mots de passe ne correspondent pas',
        mustAcceptTerms: 'Vous devez accepter les conditions',

        // Landing
        heroTitle: 'Factures Professionnelles en Secondes',
        heroSubtitle: 'Le moyen le plus simple de gérer les factures et les finances pour les petites entreprises',
        getStarted: 'Commencer',
        learnMore: 'En savoir plus',
        features: 'Fonctionnalités',
        pricing: 'Tarifs',
        perMonth: '/ mois',
        freeTrial: 'Essai gratuit',
        mostPopular: 'Le plus populaire',
        multiLanguageInvoices: 'Factures multilingues',
        multiLanguageInvoicesDesc: 'Créez des factures en 5 langues',
        financialTracking: 'Suivi financier',
        financialTrackingDesc: 'Suivez les revenus, les dépenses et les bénéfices',
        industryTemplates: 'Modèles sectoriels',
        industryTemplatesDesc: 'Automobile et entreprise générale',
        secureStorage: 'Stockage sécurisé',
        secureStorageDesc: 'Vos données sont sécurisées et cryptées',
        mobileResponsive: 'Responsive mobile',
        mobileResponsiveDesc: 'Fonctionne parfaitement sur tous les appareils',
        customBranding: 'Image de marque personnalisée',
        customBrandingDesc: 'Ajoutez votre logo et les détails de votre entreprise',
        onlinePaymentsDesc: 'Acceptez les paiements via PayPal et Stripe',
        fastEasy: 'Rapide et facile',
        fastEasyDesc: 'Créez des factures en quelques secondes',
        unlimitedInvoices: 'Factures illimitées',
        basicReports: 'Rapports de base',
        emailSupport: 'Support par email',
        mobileAccess: 'Accès mobile',
        everythingInStandard: 'Tout dans Standard',
        advancedReports: 'Analyses et rapports avancés',
        apiIntegrations: 'Intégrations API (Stripe, PayPal)',
        prioritySupport: 'Support prioritaire',
        multiUser: 'Accès multi-utilisateurs',
        customDomain: 'Domaine personnalisé',
        startPremium: 'Commencer Premium',
        featuresSubtitle: 'Tout ce dont vous avez besoin pour gérer vos finances professionnelles',
        pricingSubtitle: 'Choisissez le plan qui vous convient',
        footerTagline: 'Facturation professionnelle simplifiée',
        product: 'Produit',
        company: 'Entreprise',
        about: 'À propos',
        contact: 'Contact',
        privacy: 'Confidentialité',
        terms: 'Conditions',
        perYear: '/ an',
        appInAction: 'Voir BayRechnung en action',
        appInActionDesc: 'Créez des factures professionnelles en quelques clics',
        easyInvoiceCreation: '⚡ Création facile de factures',
        easyInvoiceCreationDesc: 'L\'interface intuitive rend la création de factures rapide et simple. Ajoutez des articles, les totaux sont calculés automatiquement.',
        professionalPDFs: '📄 PDF professionnels',
        professionalPDFsDesc: 'Générez de belles factures prêtes à imprimer qui impressionnent vos clients et répondent aux exigences légales.',
        paidInvoices: 'Factures payées',
        overdueInvoices: 'Factures en retard',
        topClients: 'Meilleurs clients',
        recurringInvoices: 'Factures récurrentes',
        recurringInvoicesDesc: 'Modèles pour la facturation régulière.',
        createTemplate: 'Créer un modèle',
        frequency: 'Fréquence',
        weekly: 'Hebdomadaire',
        monthly: 'Mensuel',
        quarterly: 'Trimestriel',
        yearly: 'Annuel',
        upcoming: 'à venir'
    },
    es: {
        dashboard: 'Panel de control',
        newInvoice: 'Nueva factura',
        archive: 'Archivo',
        reports: 'Informes',
        expenses: 'Gastos',
        recurring: 'Recurrente',
        settings: 'Configuración',
        save: 'Guardar',
        cancel: 'Cancelar',
        delete: 'Eliminar',
        edit: 'Editar',
        print: 'Imprimir',
        loading: 'Cargando...',
        total: 'Importe total',
        status: 'Estado',
        date: 'Fecha',
        customer: 'Cliente',
        invoiceNumber: 'Nº de factura',
        saveAndPrint: 'Guardar e Imprimir',
        actions: 'Acciones',
        back: 'Volver',
        welcome: 'Bienvenido',
        revenue: 'Ingresos totales',
        netProfit: 'Beneficio neto',
        recentInvoices: 'Facturas recientes',
        overviewText: 'Aquí tienes un resumen de tus facturas y finanzas.',
        companySettings: 'Ajustes de empresa',
        language: 'Idioma',
        appLanguageLabel: 'Idioma de la aplicación',
        invoiceLanguageLabel: 'Idioma de la factura (PDF)',
        plan: 'Plan',
        standard: 'Estándar',
        premium: 'Premium',
        bankDetails: 'Datos bancarios',
        onlinePayments: 'Pagos online',
        generalInfo: 'Información general',
        taxSettings: 'Ajustes de impuestos',
        currency: 'Moneda',
        taxRate: 'Tasa de impuestos',
        companyName: 'Nombre de la empresa',
        owner: 'Propietario',
        street: 'Calle',
        houseNum: 'Nº de casa',
        zip: 'Código postal',
        city: 'Ciudad',
        phone: 'Teléfono',
        email: 'Email',
        taxId: 'ID fiscal',
        vatId: 'NIF IVA',
        bankName: 'Nombre del banco',
        iban: 'IBAN',
        paymentTerms: 'Condiciones de pago',
        paymentInfo: 'Información de pago',
        taxInfo: 'Información fiscal',
        customerInfo: 'Información del cliente',
        vehicleDetails: 'Vehículo y detalles',
        items: 'Artículos / Servicios',
        description: 'Descripción',
        quantity: 'Cantidad',
        price: 'Precio unitario',
        addRow: 'Añadir fila',
        subtotal: 'Subtotal',
        tax: 'IVA',
        vehicle: 'Vehículo',
        plate: 'Matrícula',
        km: 'Kilometraje',
        draft: 'Borrador',
        sent: 'Enviado',
        paid: 'Pagado',
        partial: 'Parcial',
        overdue: 'Vencido',
        invoiceDetails: 'Detalles de la factura',
        printPdf: 'Imprimir / PDF',
        payOnline: 'Pagar en línea',
        payWithPaypal: 'Pagar con PayPal',
        payWithStripe: 'Pagar con tarjeta de crédito',
        invoiceNotFound: 'Factura no encontrada',
        backToArchive: 'Volver al archivo',
        noRecurring: 'No hay facturas recurrentes configuradas.',
        spareParts: 'Repuestos',
        receipts: 'Recibos',
        export: 'Exportar',
        addExpense: 'Añadir gasto',
        amount: 'Importe',
        noData: 'No hay datos disponibles',
        category: 'Categoría',
        rent: 'Alquiler / Gastos',
        marketing: 'Marketing',
        software: 'Software / Abos',
        insurance: 'Seguros',
        others: 'Otros',
        businessStats: 'Estadísticas de la empresa',
        industry: 'Sector',
        automotive: 'Taller mecánico',
        generalService: 'Servicio general / Comercio',
        projectDetails: 'Proyecto y referencia',
        reference: 'Número de referencia',
        extraNote: 'Información adicional',
        genericService: 'Servicio / Producto',
        inProfit: 'En Beneficio',
        inLoss: 'En Pérdida',
        logoDisplayMode: 'Visualización Logo y Nombre',
        logoOnly: 'Solo Logo',
        nameOnly: 'Solo Nombre de la Empresa',
        bothLogoOnTop: 'Ambos - Logo arriba',
        premiumApiSection: 'Interfaces de Pago (Panel API)',
        premiumApiHint: '* Estos datos se utilizan en el plan Premium para procesar pagos automáticamente a través de Stripe y PayPal.',
        premiumOnly: 'SOLO PREMIUM',
        saveSuccessful: '¡Guardado con éxito!',

        // Auth
        login: 'Iniciar sesión',
        register: 'Registrarse',
        logout: 'Cerrar sesión',
        password: 'Contraseña',
        confirmPassword: 'Confirmar contraseña',
        fullName: 'Nombre completo',
        createAccount: 'Crear cuenta',
        alreadyHaveAccount: '¿Ya tienes una cuenta?',
        noAccount: '¿No tienes cuenta?',
        signUp: 'Registrarse',
        signIn: 'Iniciar sesión',
        rememberMe: 'Recuérdame',
        forgotPassword: '¿Olvidaste tu contraseña?',
        termsAgree: 'Acepto los términos y condiciones',
        welcomeBack: '¡Bienvenido de nuevo!',
        fillAllFields: 'Por favor, rellena todos los campos',
        invalidCredentials: 'Email o contraseña inválidos',
        required: 'Requerido',
        passwordMismatch: 'Las contraseñas no coinciden',
        mustAcceptTerms: 'Debes aceptar los términos',

        // Landing
        heroTitle: 'Facturas Profesionales en Segundos',
        heroSubtitle: 'La forma más sencilla de gestionar facturas y finanzas para pequeñas empresas',
        getStarted: 'Comenzar',
        learnMore: 'Saber más',
        features: 'Características',
        pricing: 'Precios',
        perMonth: '/ mes',
        freeTrial: 'Prueba gratuita',
        mostPopular: 'Más popular',
        multiLanguageInvoices: 'Facturas multilingües',
        multiLanguageInvoicesDesc: 'Crea facturas en 5 idiomas',
        financialTracking: 'Seguimiento financiero',
        financialTrackingDesc: 'Rastrea ingresos, gastos y beneficios',
        industryTemplates: 'Plantillas de industria',
        industryTemplatesDesc: 'Automotriz y negocio general',
        secureStorage: 'Almacenamiento seguro',
        secureStorageDesc: 'Tus datos están seguros y encriptados',
        mobileResponsive: 'Responsive móvil',
        mobileResponsiveDesc: 'Funciona perfectamente en todos los dispositivos',
        customBranding: 'Marca personalizada',
        customBrandingDesc: 'Añade tu logo y detalles de la empresa',
        onlinePaymentsDesc: 'Acepta pagos a través de PayPal y Stripe',
        fastEasy: 'Rápido y fácil',
        fastEasyDesc: 'Crea facturas en segundos',
        unlimitedInvoices: 'Facturas ilimitadas',
        basicReports: 'Informes básicos',
        emailSupport: 'Soporte por email',
        mobileAccess: 'Acceso móvil',
        everythingInStandard: 'Todo en Estándar',
        advancedReports: 'Análisis e informes avanzados',
        apiIntegrations: 'Integraciones API (Stripe, PayPal)',
        prioritySupport: 'Soporte prioritario',
        multiUser: 'Acceso multiusuario',
        customDomain: 'Dominio personalizado',
        startPremium: 'Comenzar Premium',
        featuresSubtitle: 'Todo lo que necesitas para gestionar las finanzas de tu negocio',
        pricingSubtitle: 'Elige el plan que se adapte a tus necesidades',
        footerTagline: 'Facturación profesional simplificada',
        product: 'Producto',
        company: 'Empresa',
        about: 'Acerca de',
        contact: 'Contacto',
        privacy: 'Privacidad',
        terms: 'Términos',
        perYear: '/ año',
        appInAction: 'Ver BayRechnung en acción',
        appInActionDesc: 'Crea facturas profesionales con solo unos clics',
        easyInvoiceCreation: '⚡ Creación fácil de facturas',
        easyInvoiceCreationDesc: 'La interfaz intuitiva hace que crear facturas sea rápido y sencillo. Añade artículos, los totales se calculan automáticamente.',
        professionalPDFs: '📄 PDFs profesionales',
        professionalPDFsDesc: 'Genera hermosas facturas listas para imprimir que impresionan a tus clientes y cumplen con los requisitos legales.',
        paidInvoices: 'Facturas pagadas',
        overdueInvoices: 'Facturas vencidas',
        topClients: 'Mejores clientes',
        recurringInvoices: 'Facturas recurrentes',
        recurringInvoicesDesc: 'Plantillas para facturación regular.',
        createTemplate: 'Crear plantilla',
        frequency: 'Frecuencia',
        weekly: 'Semanal',
        monthly: 'Mensual',
        quarterly: 'Trimestral',
        yearly: 'Anual',
        upcoming: 'próximo'
    }
};

// Helper function to detect user's browser language
export const detectUserLanguage = () => {
    // Get browser language (e.g., "en-US", "de-DE", "tr-TR")
    const browserLang = navigator.language || navigator.userLanguage;

    // Extract language code (e.g., "en", "de", "tr")
    const langCode = browserLang?.split('-')[0]?.toLowerCase();

    // Supported languages
    const supportedLangs = ['de', 'en', 'tr', 'fr', 'es'];

    // Return detected language if supported, otherwise default to English
    return supportedLangs.includes(langCode) ? langCode : 'en';
};

export const LanguageProvider = ({ children }) => {
    const [appLanguage, setAppLanguage] = useState(() => {
        return localStorage.getItem('bay_app_lang') || 'de';
    });

    const [invoiceLanguage, setInvoiceLanguage] = useState(() => {
        return localStorage.getItem('bay_invoice_lang') || 'de';
    });

    useEffect(() => {
        localStorage.setItem('bay_app_lang', appLanguage);
    }, [appLanguage]);

    useEffect(() => {
        localStorage.setItem('bay_invoice_lang', invoiceLanguage);
    }, [invoiceLanguage]);

    const t = (key) => {
        return translations[appLanguage][key] || key;
    };

    const tInvoice = (key) => {
        return translations[invoiceLanguage][key] || key;
    };

    const LANGUAGES = [
        { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
        { code: 'en', label: 'English', flag: '🇺🇸' },
        { code: 'tr', label: 'Türkçe', flag: '🇹🇷' },
        { code: 'fr', label: 'Français', flag: '🇫🇷' },
        { code: 'es', label: 'Español', flag: '🇪🇸' }
    ];

    return (
        <LanguageContext.Provider value={{
            appLanguage,
            setAppLanguage,
            invoiceLanguage,
            setInvoiceLanguage,
            t,
            tInvoice,
            LANGUAGES
        }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
